import Head from 'next/head'
import Layout from '../components/Layout/index.js'

export default function Home() {
  return (
    <div>
      <Head>
        <title>301 builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout />
    </div>
  )
}
